#!/bin/bash

if [ "$1" = "" ]; then echo "USER ERROR: please specify a configuration file"; exit -1; fi

. ./$1
ROOT_VOL_NAME=$ec2spotter_volume_name

LAUNCH_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
LAUNCH_REGION=$(echo $LAUNCH_ZONE | sed -e 's/.$//')
PUB_KEY=$(wget -q -O - http://169.254.169.254/latest/meta-data/public-keys | awk -F= '{print $2}')

echo "ROOT_VOL_NAME=${ROOT_VOL_NAME}; LAUNCH_ZONE=${LAUNCH_ZONE}; LAUNCH_REGION=${LAUNCH_REGION}; PUB_KEY=${PUB_KEY}"

export AWS_CREDENTIAL_FILE=/root/.aws.creds
. /root/.aws.creds
export AWS_ACCESS_KEY=$AWSAccessKeyId
export AWS_SECRET_KEY=$AWSSecretKey

aws ec2 describe-volumes \
	--filters Name=tag-key,Values="Name" Name=tag-value,Values="$ROOT_VOL_NAME" \
	--region ${LAUNCH_REGION} > volumes.tmp || exit -1

ROOT_ZONE=$(jq -r '.Volumes[0].AvailabilityZone' volumes.tmp)
ROOT_VOL=$(jq -r '.Volumes[0].VolumeId' volumes.tmp)
ROOT_TYPE=$(jq -r '.Volumes[0].VolumeType' volumes.tmp)

echo "ROOT_ZONE=${ROOT_ZONE}; ROOT_TYPE=$ROOT_TYPE; ROOT_VOL=$ROOT_VOL";

if [ "$ROOT_VOL_NAME" = "" ]
then
  echo "root volume lacks a Name tag";
  exit -1;
fi

cat >user-data.tmp <<EOF
#!/bin/sh
echo AWSAccessKeyId=$AWSAccessKeyId > /root/.aws.creds
echo AWSSecretKey=$AWSSecretKey >> /root/.aws.creds

apt-get install -y git

cd /root
git clone https://github.com/atramos/ec2-spotter.git

cd ec2-spotter
./ec2spotter-setup
./ec2spotter-remount-root ${ROOT_VOL_NAME} --force
EOF

userData=$(base64 user-data.tmp | tr -d '\n');

cat >specs.tmp <<EOF
{
  "KeyName" : "$PUB_KEY",
  "InstanceType": "$ec2spotter_instance_type",
  "ImageId" : "$ec2spotter_preboot_image_id",
  "UserData" : "${userData}",
  "BlockDeviceMappings": [
    {
      "DeviceName" : "/dev/sda1",
      "Ebs": {
        "VolumeSize": 8,
        "DeleteOnTermination": true,
        "VolumeType" : "gp2"
      }
    }
  ]
}
EOF

aws ec2 request-spot-instances --spot-price $ec2spotter_bid_price --type persistent --launch-specification file://specs.tmp --region ${LAUNCH_REGION} > spot.tmp

SPOT_ID=$(jq -r '.SpotInstanceRequests[0].SpotInstanceRequestId' spot.tmp)

echo SPOT_ID=$SPOT_ID

aws ec2 create-tags --resources ${SPOT_ID} --tags Key=Name,Value=${ROOT_VOL_NAME} --region ${LAUNCH_REGION}
