#!/bin/sh
# script that runs on the permanent control host to reclaim IP address when spot instance dies.

if [ -f /var/run/ec2spotter ]
then
	# safety check - I'm not the control, I'm the spot instance!
	exit 0
fi

cd `dirname $0`
. ./$(hostname -s).conf || exit 1

ipOwner=$(aws ec2 describe-addresses --allocation-ids $ec2spotter_elastic_ip | jq -r '.Addresses[0].InstanceId')
self=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

if [ $ipOwner = "" ]
then
	# reclaim the public IP address
	aws ec2 associate-address --instance-id $self --allocation-id $ec2spotter_elastic_ip --allow-reassociation
fi
